# Generated by Django 3.1.1 on 2021-03-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companyapp", "0002_auto_20210312_1935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email",
                to="companyapp.company",
            ),
        ),
        migrations.AlterField(
            model_name="fax",
            name="fax_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fax",
                to="companyapp.company",
            ),
        ),
        migrations.AlterField(
            model_name="linkedin",
            name="linkedin_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linkedin",
                to="companyapp.company",
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="phone_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone",
                to="companyapp.company",
            ),
        ),
        migrations.AlterField(
            model_name="picupload",
            name="picupload_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picupload",
                to="companyapp.company",
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="website_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="website",
                to="companyapp.company",
            ),
        ),
        migrations.AlterField(
            model_name="whatsapp",
            name="whatsapp_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp",
                to="companyapp.company",
            ),
        ),
    ]
