# Generated by Django 3.1.1 on 2021-03-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyapp", "0003_auto_20210314_2052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="indian_presence",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="remarks",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="services",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
