# Generated by Django 3.1.1 on 2021-03-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyapp", "0004_auto_20210315_1028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="indian_presence",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="remarks",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
